version: "3.9"

services:
  server:
    build: ./server
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=your-mongodb-connection-string
    networks:
      - app-network

  client:
    build: ./client
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
